services:
  emqx1:
    image: emqx/emqx:5.8.6
    container_name: emqx1
    environment:
    - "EMQX_NODE_NAME=emqx@node1.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"

    - EMQX_LISTENER__SSL__EXTERNAL__KEYFILE=/certs/server.key
    - EMQX_LISTENER__SSL__EXTERNAL__CERTFILE=/certs/server.crt
    - EMQX_LISTENER__SSL__EXTERNAL__CACERTFILE=/certs/ca.crt

    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
        - node1.emqx.io
    ports:
      - "1883:1883"     # MQTT protocol
      - "8883:8883"     # MQTT over SSL
      - "8083:8083"     # WebSocket
      - "8084:8084"     # WebSocket Secure
      - "18083:18083"   # Dashboard
      # Default login:
      # Username: admin
      # Password: public


    volumes:
      - emqx1_data:/opt/emqx/data
      - ./emqx_certs:/certs


  emqx2:
    image: emqx/emqx:5.8.6
    container_name: emqx2
    environment:
    - "EMQX_NODE_NAME=emqx@node2.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
        - node2.emqx.io
    volumes:
      - emqx2_data:/opt/emqx/data

volumes:
  emqx1_data:
  emqx2_data:

networks:
  emqx-bridge:
    driver: bridge